name: CI devops 2024
on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Vérification du code source
      - uses: actions/checkout@v2.5.0

      # Configuration du JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build et test avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-22.04
  steps:
    - uses: actions/checkout@v2.5.0
    - name: Build image and push backend
      uses: docker/build-push-action@v3
      with:
        context: ./simple-api
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
        push: ${{ github.ref == 'refs/heads/main' }}
